#! /bin/sh

# extracts, patches and installs the fglrx. Will select the right patch for
# the kernel version

# must be run as root
if [[ `id -u` -ne "0" ]]
then
	echo 'must be run as root (do not use sudo)'
	exit 1
fi

# to avoid using lexical sort on releases, convert to numbers
function ver2num
{
n1=`echo $1 | cut -d '.' -f 1`
n2=`echo $1 | cut -d '.' -f 2`
n3=`echo $1 | cut -d '.' -f 3 | sed -e "s/\-.*//"`
echo $(($n1*10000+$n2*100+$n3))
}

echo kernel version: `uname -r`

k_ver=$(ver2num `uname -r` )

if [[ $k_ver < $(ver2num "4.6.4") ]]
then
	patchfile=fglrx_kernel_4.4.diff
elif [[ $k_ver < $(ver2num "4.7.0") ]]
then
	patchfile=fglrx_kernel_4.6.diff
elif [[ $k_ver < $(ver2num "4.9.0") ]]
then
	patchfile=fglrx_kernel_4.7.diff
elif [[ $k_ver < $(ver2num "4.10.0") ]]
then
	patchfile=fglrx_kernel_4.9.diff
elif [[ $k_ver < $(ver2num "4.11.0") ]]
then
	patchfile=fglrx_kernel_4.10.diff
elif [[ $k_ver < $(ver2num "4.12.0") ]]
then
	patchfile=fglrx_kernel_4.11.diff
elif [[ $k_ver < $(ver2num "4.13.0") ]]
then
	patchfile=fglrx_kernel_4.12.diff
else
	patchfile=fglrx_kernel_4.13.diff
fi

if [ -f $patchfile ]
then
	echo using patch $patchfile
else
	echo missing patch file: $patchfile
	exit 2
fi

echo cleaning any old fglrx-install directories
\rm -rf fglrx-install.*

# extract 
./amd-driver-installer-15.302-x86.x86_64.run --extract
install_dir=fglrx-install.*

echo using install directory $install_dir

# so the non-root can work with it
chmod -R 777 $install_dir

cd $install_dir
patch -p1 < ../$patchfile
./ati-installer.sh 15.302 --install
